### ISSUE TITLE
Function stored in a global variable is not preprocessed

### ISSUE THREAD

**Issue by viktormalik** [viktormalik/diffkemp#104]
If a function is not (transitively) called by the compared function but it is stored inside a global variable (or one of its fields) that is being used, it is not preprocessed. This may cause errors since important passes are not run over the function.

This can be reproduced by comparing `bdget` between 2.6.32-696 and 2.6.32-754 versions. The function `set_bit` contains an inline assembly code that is not replaced by an abstraction, which causes a segfault. The root of the problem is that the function `blkdev_writepage` (from which `set_bit` is transitively called) is not called but it is stored in a global variable `def_blk_aops` that is used by `bdget`.

**Comment by lenticularis39** [comment]
This also affets kernel versions 4.18.0-80.el8 and 4.18.0-107.el8 (KABI function `uv_setup_irq`) where the function `uv_domain_free` is stored inside a constant initializer (of a structure type) in a global variable and then it gets compared when comparing the constant.
