### ISSUE TITLE
Add LLVM version to snapshots

### ISSUE THREAD

**Issue by lenticularis39** [viktormalik/diffkemp#199]
There tend to be some incompatibilities between LLVM IR of different LLVM versions, leading to a snapshot generated by one version non-readable by DiffKemp built against other version. Currently this can cause a "mysterious" segmentation fault; if the LLVM version was added to the snapshot, a warning/error could be printed when attempting to use such a snapshot.

**Comment by viktormalik** [comment]
This is a good idea, I've run into this issue myself multiple times.

**Comment by lenticularis39** [comment]
Perhaps a warning on a minor version difference and an error on a major version difference would work.
