### ISSUE TITLE
Support LLVM 14

### ISSUE THREAD

**Issue by viktormalik** [viktormalik/diffkemp#227]
LLVM 14 has been released in March, we should support it ASAP.

**Comment by zacikpa** [comment]
I will require some help with this.

If I understand correctly, LLVM IR is currently transitioning to so-called _opaque pointer types_ ([relevant article](https://llvm.org/docs/OpaquePointers.html)). For us, this means that we won't be able to use the `PointerType::getElementType()` to determine the type being pointed to (as e.g. [here](https://github.com/viktormalik/diffkemp/blob/06f92b0e8e3257aedca587f6d50d50615a69bfac/diffkemp/simpll/Utils.cpp#L271)). 

I do not yet understand the code well enough to fix this. Is there some simple workaround?

**Comment by viktormalik** [comment]
Ah, I forgot about the opaque pointers. It's probably a good idea to transition as soon as possible, so let's do it now.

The issue is that LLVM pointers do not contain the pointee type information anymore. There's no single workaround here, however, the article that you linked above has some migration instructions which could be of help to us. The idea is that the correct type can be usually taken from the context. So, for each occurrence of `Type::getElementType` or `Type::getPointerElementType`, you have to check the value that the type is taken from and try to determine the type from it.

For example [here](https://github.com/viktormalik/diffkemp/blob/master/diffkemp/simpll/passes/FunctionAbstractionsGenerator.cpp#L56-L58):
```
auto FunType = dyn_cast<FunctionType>(
    dyn_cast<PointerType>(CalledType)
        ->getElementType());
```
This is extracting a function type from a call instruction. Instead of doing the above, it should be sufficient to do:
```
auto FunType = CallInst->getFunctionType();
```

For other cases, it won't be that easy, though. For example, the case that you linked is a function that checks if a value is a pointer to a struct and returns the struct type. This is no longer possible, so you'll have to check how the function is used exactly and try to figure out a different solution (e.g. if the value is always an instruction, it should be possible to extract the struct type from the instruction directly - see the migration instructions).
