### ISSUE TITLE
Logging: do not dump function values

### ISSUE THREAD

**Issue by viktormalik** [viktormalik/diffkemp#260]
If a difference is found in a function call, the logger (with `-d` set) prints the entire function bodies of the called functions. This pollutes the output (the functions can be quite long) and doesn't provide any relevant information.

Reproducer: `deferred_free_range` function between `linux-4.18.0-80.el8` and `linux-4.18.0-147.el8`.

**Comment by PLukas2018** [comment]
Resolved by #320 .
