### ISSUE TITLE
Install viewer to system

### ISSUE THREAD

**Issue by viktormalik** [viktormalik/diffkemp#277]
Currently, viewer requires the `view` directory to be located relatively to the `diffkemp.py` file (see [diffkemp.py](https://github.com/viktormalik/diffkemp/blob/2db77b5759bd5b3f889d078af2932a2db1affbd8/diffkemp/diffkemp.py#L582)). This is not possible when DiffKemp is installed to the system, e.g. from the RPM file or using `ninja install -C build && pip install .`

We should figure out a way to install the viewer to the system and update `diffkemp view` to use the installed version, if the local one doesn't exist (something similar to what we do for the [SimpLL binary](https://github.com/viktormalik/diffkemp/blob/master/diffkemp/simpll/simpll.py#L118-L123)).

IIUC, one of the problems is that `diffkemp view` needs to write source and diff files into `view/build/`, which will be problematic if `view/` is installed in a system path. Perhaps we could update the viewer such that we can pass it the `build/` directory upon executing `npm prod run`.

It would be also nice if we could build the viewer as a static site but that sounds even more complicated w.r.t. accessing local files.

cc @PLukas2018

**Comment by PLukas2018** [comment]
I came up with 3 possible solutions:
1. **Build the viewer as a static site** (without using the server): There is the problem with accessing local files.
    - Possibilities to access local files:
        1. Using **AJAX** (fetch, XMLHttpRequest) is not an option ([CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default)).
        2. Using a **folder picker** ([File System API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API), [drag and drop](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/getAsFileSystemHandle), [`<input type="file">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file)) -- the disadvantage is that user has to pick a folder (which would contain src files and diffs) in the browser.
        3. Other options?
2. **More clever backend/server**:
    - Create a more clever server that would run the result viewer and serve him src and diff files from a specified local directory.
    - The server and the `build` folder would need to be probably installed (should be enough as read-only).  
    - The server could read the src files of the compared project from the project folder and provide it to the browser (the result viewer).
    - The diffs could be placed in something like `~/.diffkemp`, `/var/lib/diffkemp`, `/var/cache/diffkemp`, or something like that and accessed via the server.
    - In the future, I guess using the server could allow browsing results of multiple compared versions of a program.
    - In the future, I think it could be possible to allow code navigation (e.g. clicking on a called function leads to a source file with its definition, ...) thanks to being able to easily access local files (all src files of the project) through the server.
3. **Static server** (little changes in current solution):
    - In installation would be necessary to copy/move the build directory to `~/.diffkemp`, `/var/lib/diffkemp`, or something like that.
    - Then in the invocation of `bin/diffkemp` would be necessary to check if `diffkemp/view` directory exists (as you mentioned) if not use eg. `~/.diffkemp/build` for copying the src files and creating diffs.
    - Installing/saving the `view` directory should not be even necessary because it should be possible to run the viewer directly with `npx serve ~/.diffkemp/build` (or `python3 -m http.server --directory ~/.diffkemp/build/ ` or similar).
    - It would not be possible to run a development server when installed like this but I think it does not matter too much.

Personally, I think that option number 3 should be probably the easiest and fastest solution. In the future, we could use option number 2 which could be a better solution.

**Comment by viktormalik** [comment]
Thanks for the detailed analysis!

> Personally, I think that option number 3 should be probably the easiest and fastest solution. In the future, we could use option number 2 which could be a better solution.

Agreed. Option 2 will make much more sense once we deploy it to a server so that the comparison results are available online.

Option 3 seems the best at this point. I believe that `/var/lib/diffkemp/view/` is the right place to install the `view/build` directory to. Then, as already mentioned, `diffkemp view` will check if local `view` directory exists, and if not, will fallback to `/var/lib/diffkemp/view` to search for a production build. Development build won't be necessary.

**Comment by viktormalik** [comment]
Resolved by #278.
